services:
  php: # docker-compose run php bash
    build: './.docker/php'
    tty: true
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/var/www/html/
      - ./.docker/php/logs/access.log:/var/log/apache2/access.log
      - ./.docker/php/logs/error.log:/var/log/apache2/error.log
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  composer:
    build: './.docker/composer'
    tty: true
    command: ["composer", "install"]
    volumes:
      - ./:/app/
    depends_on:
      - php